<?php

$root = getenv('PLUGIN_ROOT') ?: dirname(__DIR__);
$preview_class = file_get_contents($root . '/includes/class-parcs-ht-admin-shortcode-preview.php');
$js = file_get_contents($root . '/assets/admin-shortcode-preview.js');

function live_render_regression($condition, $message) {
    if (!$condition) { fwrite(STDERR, $message . PHP_EOL); exit(1); }
    echo '[OK] ' . $message . PHP_EOL;
}

live_render_regression(strpos($preview_class, "Parcs_HT_Shortcodes::render('page', 'fr', array())") !== false, 'Preview source is generated by the public shortcode renderer');
live_render_regression(strpos($preview_class, "wp_dequeue_script('parcs-ht-frontend')") !== false && strpos($preview_class, "wp_dequeue_style('parcs-ht-frontend')") !== false, 'Duplicate frontend assets are prevented in wp-admin');
live_render_regression(strpos($js, 'parcs-ht-real-shortcode-preview-source') !== false, 'Rendered shortcode source is moved into the visible preview canvas');
live_render_regression(strpos($js, "while(source.firstChild)canvas.appendChild(source.firstChild)") !== false, 'The complete shortcode DOM is preserved instead of being redrawn as a fake demo');
live_render_regression(strpos($js, "canvas.style.backgroundColor=picker.value") !== false, 'Background simulation changes only the preview canvas');
live_render_regression(strpos($js, 'Desktop') === false && strpos($js, 'Mobile') === false, 'Removed device simulation stays removed from the simplified preview');

echo "Admin real shortcode preview render regression: OK\n";
